language: objective-c
osx_image: xcode7
podfile: Example/Podfile

before_install:
    - gem install cocoapods --quiet
    - "xcrun instruments -w 'iPhone 5 (9.0)' || true"
    - sleep 20
    - sleep 20
    - sleep 20
    - perl allowAccess
    - brew uninstall xctool && brew install --HEAD xctool

script:
    - "xctool -workspace Example/SwiftAddressBookExample.xcworkspace -sdk iphonesimulator -scheme SwiftAddressBookTests -destination platform='iOS Simulator','OS=9.0',name='iPhone 5' build test"
